language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get update
install:
  # Packages needed for testing
  - pip install nose coverage python-coveralls nose-timer
  # INDRA-DB dependencies
  - pip install boto3 sqlalchemy psycopg2-binary pgcopy flask nltk reportlab
        matplotlib
  # INDRA dependencies
  - pip install git+https://github.com/sorgerlab/indra.git
  # DB Preassembly pickles
  - cd $TRAVIS_BUILD_DIR/indra_db/tests
  - wget http://sorger.med.harvard.edu/data/bgyori/test_text_ref_tuples.pkl -nv
  - wget http://sorger.med.harvard.edu/data/bgyori/test_text_content_tuples.pkl -nv
  - wget http://sorger.med.harvard.edu/data/bgyori/test_reading_tuples.pkl -nv
  - wget http://sorger.med.harvard.edu/data/bgyori/test_db_info_tuples.pkl -nv
  - wget http://sorger.med.harvard.edu/data/bgyori/test_stmts_tuples.pkl -nv
  - pip list
before_script:
  # Enable plotting on fake display
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
  # Run standard unit tests
  - cd $TRAVIS_BUILD_DIR
  # doctests on Travis would otherwise fail
  - export NOSEATTR="";
  - if [[ $TRAVIS_PULL_REQUEST ]]; then
      export NOSEATTR="!nonpublic";
    fi
  - if [[ $RUN_SLOW != "true" ]]; then
      export NOSEATTR="!slow,$NOSEATTR";
    fi
  # Now run all INDRA_DB tests
  - nosetests indra_db -v -a $NOSEATTR
        --with-coverage --cover-inclusive --cover-package=indra
        --with-doctest --with-timer --timer-top-n 10
  - cd $TRAVIS_BUILD_DIR
  # Run code style report on diff
  - git remote set-branches --add origin master
  - git fetch
  - git diff origin/master | pycodestyle --diff > pep8.txt; cat pep8.txt;
after_success:
  - coveralls
