language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.6"
services:
  - postgresql
  - xvfb
addons:
  postgresql: "9.6"
  apt:
    packages:
      - libssl1.0.0
before_install:
  - sudo apt-get update
  - sudo apt-get install openjdk-8-jdk
  - pip install numpy scipy sympy cython nose lxml matplotlib==1.5.0 pandas
        awscli
install:
  # REACH
  - pip install git+https://github.com/kivy/pyjnius.git@1cbfef
  - wget http://sorger.med.harvard.edu/data/bachman/reach-82631d-biores-e9ee36.jar -nv
  - export REACHPATH=$TRAVIS_BUILD_DIR/reach-82631d-biores-e9ee36.jar
  # INDRA dependencies
  - pip install coverage python-coveralls boto3 sqlalchemy psycopg2-binary pgcopy nose-timer flask nltk reportlab pybel
  - pip install git+https://github.com/bgyori/paths_graph.git@networkx2
  - pip install doctest-ignore-unicode
  - pip install git+https://github.com/pagreene/indra.git@biopax_impl
  # INDRA-DB dependencies
  - pip install .[test]
  # DB Preassembly pickles
  - cd $TRAVIS_BUILD_DIR/indra_db/tests
  - if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then
      aws s3 cp s3://bigmech/indra-db/test_resources/db_pa_test_input_1M_public.pkl db_pa_test_input_1M.pkl --no-sign-request;
    else
      aws s3 cp s3://bigmech/indra-db/test_resources/db_pa_test_input_1M.pkl db_pa_test_input_1M.pkl;
    fi
  - du -sh db_pa_test_input_1M.pkl
  - cd $TRAVIS_BUILD_DIR/indra_db/resources
  - curl https://s3.amazonaws.com/bigmech/indra-db/test_resources/test_ftp.zip > test_ftp.zip
  - unzip test_ftp.zip
  - pip install -U networkx>=2
  - pip list
before_script:
  # Create a test database.
  - psql -c 'create database indradb_test;' -U postgres
  # Enable plotting on fake display
  - export DISPLAY=:99.0
  - sleep 3
script:
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
  - export SITEMAPPER_CACHE_PATH=$TRAVIS_BUILD_DIR/site_mapper_cache.pkl
  # Run standard unit tests
  - cd $TRAVIS_BUILD_DIR
  # doctests on Travis would otherwise fail
  - export NOSEATTR="!notravis,!known_failing";
  - if [[ $TRAVIS_PULL_REQUEST != "false" ]]; then
      export NOSEATTR="!nonpublic,$NOSEATTR";
    fi
  - if [[ $RUN_SLOW != "true" ]]; then
      export NOSEATTR="!slow,$NOSEATTR";
    fi
  - echo "NOSEATTR=" $NOSEATTR
  # Now run all INDRA_DB tests
  - nosetests indra_db -v -a $NOSEATTR
        --with-coverage --cover-inclusive --cover-package=indra_db
        --with-doctest --with-timer --timer-top-n 10
  - cd $TRAVIS_BUILD_DIR
  # Run code style report on diff
  - git remote set-branches --add origin master
  - git fetch
  - git diff origin/master | pycodestyle --diff > pep8.txt; cat pep8.txt;
after_success:
  - coveralls
